zcoinofficial/ztm

src/Ztm.ServiceModel.Tests/BackgroundServiceTests.cs, src/Ztm.ServiceModel.Tests/ServiceManagerTests.cs, src/Ztm.ServiceModel.Tests/ServiceTests.cs, src/Ztm.ServiceModel.Tests/TestBackgroundService.cs, src/Ztm.ServiceModel.Tests/TestService.cs, src/Ztm.ServiceModel/BackgroundService.cs, src/Ztm.ServiceModel/IService.cs, src/Ztm.ServiceModel/Service.cs, src/Ztm.ServiceModel/ServiceManager.cs, src/Ztm.Zcoin.Synchronization.Tests/BlocksSynchronizerTests.cs, src/Ztm.Zcoin.Synchronization/BlocksSynchronizer.cs
This also remove `Name` property from service too. After using service framework for a while I found out that it not useful.
=> Improve and fixes service framework

src/Ztm.Threading.Tests/ShutdownGuardTests.cs, src/Ztm.Threading/ShutdownGuard.cs, src/Ztm.Threading/Timer.cs
closes https://github.com/zcoinofficial/ztm/issues/29
=> Rename ShutdownEvent to ShutdownGuard

Jenkinsfile, README.md, src/Ztm.Configuration/Ztm.Configuration.csproj, src/Ztm.Data.Entity.Postgres/Ztm.Data.Entity.Postgres.csproj, src/Ztm.Data.Entity/Ztm.Data.Entity.csproj, src/Ztm.WebApi/Ztm.WebApi.csproj, src/Ztm.Zcoin.NBitcoin.Tests/Ztm.Zcoin.NBitcoin.Tests.csproj, src/Ztm.Zcoin.NBitcoin/Ztm.Zcoin.NBitcoin.csproj, src/Ztm.Zcoin.Rpc.Tests/Ztm.Zcoin.Rpc.Tests.csproj, src/Ztm.Zcoin.Rpc/Ztm.Zcoin.Rpc.csproj, src/Ztm.Zcoin.Synchronization/AddressWatcher.cs, src/Ztm.Zcoin.Synchronization/Ztm.Zcoin.Synchronization.csproj, src/Ztm.Zcoin.Testing/Ztm.Zcoin.Testing.csproj
resolve https://github.com/zcoinofficial/ztm/issues/31
=> Remove nbitcoin submodule

src/Ztm.Zcoin.NBitcoin.Tests/BlockHeaderExtensionsTests.cs, src/Ztm.Zcoin.NBitcoin/BlockHeaderExtensions.cs, src/Ztm.Zcoin.NBitcoin/RPC/ZcoinRPCClient.cs, src/Ztm.Zcoin.NBitcoin/ZcoinBlock.cs, src/Ztm.Zcoin.NBitcoin/ZcoinConsensusFactory.cs, src/Ztm.Zcoin.Rpc/IZcoinRpcClient.cs, src/Ztm.Zcoin.Rpc/ZcoinRpcClient.cs, src/Ztm.Zcoin.Synchronization.Tests/BlocksStorageTests.cs, src/Ztm.Zcoin.Synchronization/BlocksStorage.cs
resolve https://github.com/zcoinofficial/ztm/issues/34
=> Add header extension

src/Ztm.WebApi/CallbackResult.cs
resolves https://github.com/zcoinofficial/ztm/issues/47
=> Add callback result

src/Ztm.Configuration.Tests/BitcoinAddressConfigurationConverterTests.cs, src/Ztm.Configuration/BitcoinAddressConfiguration.cs, src/Ztm.Configuration/BitcoinAddressConfigurationConverter.cs
resolve https://github.com/zcoinofficial/ztm/issues/44
=> Add bitcoin address configuration and converter

src/Ztm.WebApi.Tests/TokenAmountModelBinderProviderTests.cs, src/Ztm.WebApi.Tests/TokenAmountModelBinderTests.cs, src/Ztm.WebApi.Tests/Ztm.WebApi.Tests.csproj, src/Ztm.WebApi/Binders/TokenAmountModelBinder.cs, src/Ztm.WebApi/Binders/TokenAmountModelBinderProvider.cs, src/Ztm.WebApi/Startup.cs, src/Ztm.Zcoin.Synchronization/BlocksRetriever.cs, src/Ztm.sln
=> Add TokenAmountModelBinder

src/Ztm.Data.Entity/Contexts/Main/Block.cs, src/Ztm.Data.Entity/Contexts/Main/BlockTransaction.cs, src/Ztm.Data.Entity/Contexts/Main/Input.cs, src/Ztm.Data.Entity/Contexts/Main/Output.cs, src/Ztm.Data.Entity/Contexts/Main/Transaction.cs, src/Ztm.Data.Entity/Contexts/Main/WebApiCallback.cs
closes https://github.com/zcoinofficial/ztm/issues/39
=> Make all ef models to be sealed

src/Ztm.Configuration.Tests/ConfigurationExtensionsTests.cs, src/Ztm.Configuration/BitcoinAddressConfiguration.cs, src/Ztm.Configuration/ZcoinConfiguration.cs, src/Ztm.WebApi/appsettings.json
=> Add configurations for issuer and distributor

.gitmodules
closes https://github.com/zcoinofficial/ztm/issues/58
=> Cleanup NBitcoin submodule

src/Ztm.Data.Entity.Postgres/MainDatabase.cs, src/Ztm.Data.Entity.Testing/TestMainDatabase.cs, src/Ztm.Data.Entity/Contexts/MainDatabase.cs
close https://github.com/zcoinofficial/ztm/issues/63
=> Change db configure function to pass ModelBuilder to instead

src/Ztm.Zcoin.NBitcoin.Tests/RpcTests.cs, src/Ztm.Zcoin.Testing/NodeBuilderFactory.cs
=> Upgrade Zcoin binary from 0.13.7.10 to 0.13.8.5

src/Ztm.Zcoin.Watching.Tests/ConfirmationWatcherTests.cs, src/Ztm.Zcoin.Watching.Tests/TestConfirmationWatcher.cs, src/Ztm.Zcoin.Watching.Tests/TestWatcher.cs, src/Ztm.Zcoin.Watching.Tests/TransactionConfirmationWatcherTests.cs, src/Ztm.Zcoin.Watching.Tests/TransactionWatchTests.cs, src/Ztm.Zcoin.Watching.Tests/WatchTests.cs, src/Ztm.Zcoin.Watching.Tests/WatcherTests.cs, src/Ztm.Zcoin.Watching.Tests/Ztm.Zcoin.Watching.Tests.csproj, src/Ztm.Zcoin.Watching/BlockEventType.cs, src/Ztm.Zcoin.Watching/ConfirmationType.cs, src/Ztm.Zcoin.Watching/ConfirmationWatcher.cs, src/Ztm.Zcoin.Watching/IConfirmationWatcherHandler.cs, src/Ztm.Zcoin.Watching/ITransactionConfirmationWatcherHandler.cs, src/Ztm.Zcoin.Watching/IWatcherHandler.cs, src/Ztm.Zcoin.Watching/TransactionConfirmationWatcher.cs, src/Ztm.Zcoin.Watching/TransactionWatch.cs, src/Ztm.Zcoin.Watching/Watch.cs, src/Ztm.Zcoin.Watching/WatchRemoveReason.cs, src/Ztm.Zcoin.Watching/Watcher.cs, src/Ztm.Zcoin.Watching/Ztm.Zcoin.Watching.csproj, src/Ztm.sln
=> Move Ztm.Zcoin.Synchronization.Watchers to Ztm.Zcoin.Watching

src/Ztm.WebApi/Ztm.WebApi.csproj
=> Exclude appsettings.Development.json when deploy

src/Ztm.WebApi.Tests/Binders/BinderTests.cs, src/Ztm.WebApi.Tests/Binders/BitcoinAddressModelBinderProviderTests.cs, src/Ztm.WebApi.Tests/Binders/BitcoinAddressModelBinderTests.cs, src/Ztm.WebApi.Tests/Binders/PropertyAmountModelBinderProviderTests.cs, src/Ztm.WebApi.Tests/Binders/PropertyAmountModelBinderTests.cs, src/Ztm.WebApi.Tests/Binders/ProviderTests.cs, src/Ztm.WebApi/Binders/BitcoinAddressModelBinder.cs, src/Ztm.WebApi/Binders/BitcoinAddressModelBinderProvider.cs, src/Ztm.WebApi/Startup.cs
=> Implement model binder for BitcoinAddress

.env, Jenkinsfile, README.md, docker-compose.yml, src/Ztm.EndToEndTests/Ztm.EndToEndTests.csproj, src/Ztm.EndToEndTests/ZtmFixture.cs, src/Ztm.WebApi/appsettings.Development.json, src/Ztm.sln
This one need to pay attention for the possibility of vulnerabilities. So, please review carefully.
Resolve #109.
=> Initialize E2E tests

Jenkinsfile
=> Fix Jenkinsfile for non-PR

src/Ztm.Zcoin.Rpc.Tests/ZcoinRpcClientTests.cs, src/Ztm.Zcoin.Rpc.Tests/Ztm.Zcoin.Rpc.Tests.csproj, src/Ztm.Zcoin.Rpc/IZcoinRpcClient.cs, src/Ztm.Zcoin.Rpc/ZcoinRpcClient.cs
closes https://github.com/zcoinofficial/ztm/issues/89 and https://github.com/zcoinofficial/ztm/issues/83
=> Add rpc to send token and get balance

Jenkinsfile, src/Ztm.WebApi/Dockerfile
=> Add Dockerfile for Ztm.WebApi

src/Ztm.WebApi/Startup.cs, src/Ztm.WebApi/appsettings.json
closes https://github.com/zcoinofficial/ztm/issues/125
=> Config Mvc to use snake_case for JSON

.github/workflows/ci.yml, README.md, src/Ztm.Hosting.Tests/BackgroundServiceTests.cs, src/Ztm.Threading.Tests/TimerTests.cs, src/Ztm.Threading/Timer.cs, src/Ztm.Zcoin.NBitcoin.Tests/RpcTests.cs, src/Ztm.Zcoin.Rpc.Tests/Properties/AssemblyInfo.cs, src/Ztm.Zcoin.Rpc.Tests/ZcoinRpcClientFactoryTests.cs, src/Ztm.Zcoin.Rpc.Tests/ZcoinRpcClientTests.cs, src/Ztm.Zcoin.Testing/NodeBuilderFactory.cs
=> Add Actions for CI

src/Ztm.Threading.Tests/TimerSchedulers/ThreadPoolSchedulerTests.cs, src/Ztm.Threading.Tests/TimerTests.cs, src/Ztm.Threading.Tests/Ztm.Threading.Tests.csproj, src/Ztm.Threading/ITimerScheduler.cs, src/Ztm.Threading/Timer.cs, src/Ztm.Threading/TimerSchedulers/ThreadPoolScheduler.cs
=> Implement scheduler for Timer

src/Ztm.Data.Entity.Postgres/Migrations/20191216051138_InitializeAddressPools.Designer.cs, src/Ztm.Data.Entity.Postgres/Migrations/20191216051138_InitializeAddressPools.cs, src/Ztm.Zcoin.Rpc.Tests/ZcoinRpcClientTests.cs, src/Ztm.Zcoin.Rpc/ZcoinRpcClient.cs, src/Ztm.Zcoin.Rpc/ZcoinRpcClientFactory.cs
Web api is error when starting and trying to get genesis block.
The error message is shown below
```
crit: Ztm.Hosting.BackgroundServiceErrorLogger[0]
Fatal error occurred in Ztm.Zcoin.Synchronization.BlocksSynchronizer.
NBitcoin.RPC.RPCException: No information available about transaction
at NBitcoin.RPC.RPCResponse.ThrowIfError()
at NBitcoin.RPC.RPCClient.SendCommandAsyncCore(RPCRequest request, Boolean throwIfRPCError)
at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, Boolean throwIfRPCError)
at Ztm.Zcoin.Rpc.ZcoinRpcClient.GetExodusTransactionAsync(uint256 transaction, CancellationToken cancellationToken) in /home/thebevrishot/workspace/ztm/src/Ztm.Zcoin.Rpc/ZcoinRpcClient.cs:line 157
at Ztm.Zcoin.Rpc.ZcoinRpcClient.TryDecodeExodusTransaction(Transaction transaction) in …
```
=> Fix fail to get genesis block

.github/workflows/ci.yml
closes https://github.com/zcoinofficial/ztm/issues/118
=> Add attaching the migration file to the db docker on e2e testing configuration

src/Ztm.Threading.Tests/TimerSchedulers/ThreadPoolSchedulerTests.cs
closes https://github.com/zcoinofficial/ztm/issues/140
=> Increase timeout for Ztm.Threading.Tests.TimerSchedulers.ThreadPoolSchedulerTests.Schedule_WithNonNullPeriod_ShouldNotOneShot 

src/Ztm.Configuration.Tests/Ztm.Configuration.Tests.csproj, src/Ztm.Configuration/Ztm.Configuration.csproj, src/Ztm.Data.Entity.Postgres.Tests/Ztm.Data.Entity.Postgres.Tests.csproj, src/Ztm.Data.Entity.Postgres/Ztm.Data.Entity.Postgres.csproj, src/Ztm.Data.Entity.Testing/Ztm.Data.Entity.Testing.csproj, src/Ztm.Data.Entity.Tests/Ztm.Data.Entity.Tests.csproj, src/Ztm.Data.Entity/Ztm.Data.Entity.csproj, src/Ztm.EndToEndTests/Ztm.EndToEndTests.csproj, src/Ztm.Hosting.AspNetCore.Tests/Ztm.Hosting.AspNetCore.Tests.csproj, src/Ztm.Hosting.AspNetCore/Ztm.Hosting.AspNetCore.csproj, src/Ztm.Hosting.Tests/Ztm.Hosting.Tests.csproj, src/Ztm.Hosting/Ztm.Hosting.csproj, src/Ztm.ObjectModel.Tests/Ztm.ObjectModel.Tests.csproj, src/Ztm.ObjectModel/Ztm.ObjectModel.csproj, src/Ztm.Testing/Ztm.Testing.csproj, src/Ztm.Threading.Tests/Ztm.Threading.Tests.csproj, src/Ztm.Threading/Ztm.Threading.csproj, src/Ztm.WebApi.Tests/Ztm.WebApi.Tests.csproj, src/Ztm.WebApi/Ztm.WebApi.csproj, src/Ztm.Zcoin.NBitcoin.Tests/Ztm.Zcoin.NBitcoin.Tests.csproj, src/Ztm.Zcoin.NBitcoin/Ztm.Zcoin.NBitcoin.csproj, src/Ztm.Zcoin.Rpc.Tests/Ztm.Zcoin.Rpc.Tests.csproj, src/Ztm.Zcoin.Rpc/Ztm.Zcoin.Rpc.csproj, src/Ztm.Zcoin.Synchronization.Tests/Ztm.Zcoin.Synchronization.Tests.csproj, src/Ztm.Zcoin.Synchronization/Ztm.Zcoin.Synchronization.csproj, src/Ztm.Zcoin.Testing/Ztm.Zcoin.Testing.csproj, src/Ztm.Zcoin.Watching.Tests/Ztm.Zcoin.Watching.Tests.csproj, src/Ztm.Zcoin.Watching/Ztm.Zcoin.Watching.csproj
=> Enable StyleCop.Analyzers

.github/workflows/cd.yml, .github/workflows/ci.yml
closes https://github.com/zcoinofficial/ztm/issues/92
=> Add cd configuration on Github Actions

src/Ztm.Zcoin.Synchronization.Tests/BlocksRetrieverTests.cs, src/Ztm.Zcoin.Synchronization.Tests/BlocksStorageTests.cs, src/Ztm.Zcoin.Synchronization.Tests/BlocksSynchronizerTests.cs, src/Ztm.Zcoin.Synchronization/BlocksRetriever.cs, src/Ztm.Zcoin.Synchronization/BlocksStorage.cs, src/Ztm.Zcoin.Synchronization/BlocksSynchronizer.cs, src/Ztm.Zcoin.Synchronization/IBlocksRetrieverHandler.cs, src/Ztm.Zcoin.Synchronization/Ztm.Zcoin.Synchronization.csproj
=> Make BlocksRetriever handle re-org better
